### ISSUE TITLE
editor.js - live preview - resolveRelations on input

### ISSUE THREAD

**Issue by kelenakamura** [storyblok/gatsby-storyblok-boilerplate#13]
On initial load resolveRelations work, however the live update preview doesn't as the payload from storyblok just overwrites the state, but it wouldn't actually resolveRelations again.  

`
sb.on("input", payload => {
      if (this.state.story && payload.story.id === this.state.story.id) {
        payload.story.content = sb.addComments(
          payload.story.content,
          payload.story.id
        );
        this.setState({ story: payload.story });
      }
    });
`

**Comment by emanuelgsouza** [comment]
Hi, thanks for submitting this issue. We fixed this problem in our platform! You can check here: https://www.storyblok.com/cl/resolve-relations-with-storyblok-bridge
