### ISSUE TITLE
No matching version found for gatsby-source-storyblok@^0.2.3

### ISSUE THREAD

**Issue by bernardodestefano** [storyblok/gatsby-storyblok-boilerplate#5]
After npm install i got this problem, log below

[2019-04-29T09_16_25_949Z-debug.log](https://github.com/storyblok/gatsby-storyblok-boilerplate/files/3126684/2019-04-29T09_16_25_949Z-debug.log)

**Comment by bernardodestefano** [comment]
SOLVED

The target version of gatsby-source-storyblok is wrong, should target 0.2.2

**Comment by onefriendaday** [comment]
Thanks for the report! We published 0.2.3 now.
