### ISSUE TITLE
Unknown type "ImageSharpFixed" on initial run

### ISSUE THREAD

**Issue by 2metres** [storyblok/gatsby-storyblok-boilerplate#7]
```
 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ImageSharpFixed".

File: node_modules/gatsby-transformer-sharp/src/fragments.js:21:37
```

**Comment by tanvibhakta** [comment]
This was also an issue for me, and implementing https://github.com/gatsbyjs/gatsby/issues/15625 worked for me. I see that @2metres has also opened https://github.com/storyblok/gatsby-storyblok-boilerplate/pull/8 to fix this and it would be great if @onefriendaday could merge this?

Thank you for your time on this starter!

**Comment by emanuelgsouza** [comment]
Hi, thanks for submitting this issue. I'll close this issue because the `gatsby-transformer-sharp` has been already added in `gatsby.config.js`.
